# Generated by Django 3.0.8 on 2020-12-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20201209_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='no_of_pages',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
    ]
